apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- discord-day2-nl-redirect.yaml

namespace: discord-day2-nl-redirect

commonLabels:
  app: discord-day2-nl-redirect
