
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB0Q2y+nZW+zGkC5U4PFpHSjTVo8WProagTar+6nQo5HXxTSQtHtLk+VsFaKfskE1TX3IBtHHcdoJDQOZQeSO9rNnvfN5E/stHvTSiYR+tRUWh442BzPDAY6+Zo5eV2zj3E2CJ4jXDb8+azdlvcCIaj9W7qtoU0xa8wi8gNHtugrbAkV5SE1oZA3+zhg9vZAYqhdjKGG6QVVsq0uMbsPZC5c+ms1uMYRWGgqS/a6YcozTBnR6M1NJJmxwAcBBrYg/YUk6BODsXvr+8yL66HhqrcNyVimwskaUsd8l38fHagbXMmC89B4mt021ecamEw6aMrPyJQC6P1wquzoG4bZnbRKFpY5Zn7g65MvGRtiu8lk87ZyTQcofuIbtV43Ry7VNCSat1TBSXnZ6CV/zBEQ/sYDWvGWPa1V+fTZnAUkF33jyzyP3yNeJ9o1yJJpURvulnnrVARZsNDtDXaH+heV5FKMclOmrAwVlxlg0FAKMSYYIZ/KFShQsObYf96e2bJi7q44HWdEJa+docx15Lmxu8MlavF8scBLw07G6/3sO+biJa5lhU2l9XDU5kWtQEYyXiAM41Wk3PseKOv5tGluZ0MT5+U3VoMtfVIPB/Ny/ZcIxrpYVwF3Ke69sy1jd1jkS+1vUwCK81S2RQTlCHlZ0SIti8hbvyl7PIlCO7GMVFAtS7oD2laFWGcTqxQH7k7gxSpqAXKCyKnn9sOIWGYD1m+cvGTq9VUFh45WKCg5gMutWtHxyvnhO+V