---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-storage
  namespace: rancher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
