apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- external-dns.yaml

namespace: external-dns-operator

commonLabels:
  app: external-dns

secretGenerator:
- name: external-dns
  envs: 
  - secret.env
  type: Opaque
